### ISSUE TITLE
mandatory LDAP settings - shibboleth only scenarios not working

### ISSUE THREAD

**Issue by n0trax** [uniwue-rz/LoginShibboleth#3]
Hi,

there are some LDAP settings that are mandatory, even if LDAP is disabled.

I configured the plugin via config.ini.php and disabled LDAP with `ldap_active = 0` Nevertheless, i get the following error message: `Can not connect to the LDAP server.`
If i configure an existing LDAP-Server everything is fine...

Furthermore i had to set `shibboleth_view_groups_option` and `shibboleth_admin_groups_ldap_dn`, although i set `shibboleth_groups_manual_active = 1`. Just as I understand the documentation in the wiki, it should only be neccessary to set `shibboleth_groups_manual` and `shibboleth_superuser_groups`. Or have I misunderstood that?

**Comment by pouyana** [comment]
Hi,
Thanks for the report.
The Shibboleth user manager to get the Urls (view, admin) for the user needs to have access LDAP connection. This was done always even if LDAP was not active. If you have the manual access and no settings in view and admin, this should be ignored. But in the code it didn't happen. I fixed it (4031e02) please test and report.

**Comment by n0trax** [comment]
Thank you. It is working fine now.
