### ISSUE TITLE
getSiteId() works only with http protocol

### ISSUE THREAD

**Issue by YKWeyer** [uniwue-rz/LoginShibboleth#6]
[`LoginShibbolethUser::getSiteId`](https://github.com/uniwue-rz/LoginShibboleth/blob/9a35d1363529a4087cbdefe997f8713a0d185a01/LoginShibbolethUser.php#L255) expects all the URLs tested against to start with `http://`. It won't work with `https://` websites.

## Possible fixes

* Remove the protocol from `$domain` and use a `LIKE` operator:
  ```
  $domain = '%://' . $parsedDomain['path'];
  $siteId = Db::fetchOne('SELECT idsite FROM ' . Common::prefixTable('site') . ' WHERE main_url LIKE ?',
    array($domain));
  ```
* Use an `OR` condition to check both `https` and `http` protocol at the same time
* Use a `REGEXP` operator
* Don't change the code, but document this behaviour

@pouyana I'd be happy to submit a MR based on the solution that suits you best.

**Comment by Dherlou** [comment]
This is fixed in [v1.3.1](https://github.com/uniwue-rz/LoginShibboleth/releases/tag/1.3.1).
I decided to go with your suggested `REGEXP` approach, as it is the cleanest solution IMO.
